### ISSUE TITLE
masks all black (blank)

### ISSUE THREAD

**Issue by A00TB** [wisepaip/paip2020#9]
Hi,

I have downloaded the xml2mask script to test on a couple of WSIs. It appears that the masks are completley blank with no regions of interested shown (in white). I did this for training slides 45 and 7. It is worth noting I am using python 3.7 and doing preliminary work on a macbook (if that matters).

**Comment by hjoonjang** [comment]
Hi, thanks for raising a question.

I guess the reason you cannot see the tumor area from the mask images is that the masks have only 0 & 1 as pixel values though they have uint8 range, which is [0, 255]. In other words, it must be too dark to discern.

Please try applying color maps by LUT in any proper viewer, or rescaling the value by multiplying 255 right before they are saved.

If the problem persists, let us know again!

Thanks :)

**Comment by A00TB** [comment]
Great, thanks for the advice.

If anyone else comes across the issue I did what @hjoonjang said by multiplying ret[1] by 255 in line 93:

`tifffile.imsave(save_fn, (ret[1]*255).astype(np.uint8), compress=9)`

Cheers :)
